#!/bin/zsh
cat ~/.xsession-errors > ~/.xsession-errors-1
echo > ~/.xsession-errors
echo "New Session on $HOSTNAME" | figlet -w 1000

eval $(keychain --eval --nogui) 

#xrandr --output VGA1 --primary
{ sleep 1s; xbindkeys --nodaemon ; } &
{ sleep 1s; davmail ; } &

{ sleep 1s; nitrogen --restore; sleep 1s; conky; } &

{ sleep 2s; parcellite ; } &
{ sleep 2s; nm-applet ; } &
{ sleep 2s; bluetooth-applet ; } &
#{ sleep 5s; volti; } &
#{ sleep 5s; pasystray; } &
{ sleep 3s; mopidy; } &
{ sleep 3s; gnome-sound-applet; } &
{ sleep 3s; cryptkeeper; } &
{ sleep 5s; pidgin_fortune; } &

echo "Session: setting Xdefaults and Xmodmap"
[ -e ~/.Xdefaults ] && xrdb -merge ~/.Xdefaults
[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap > /dev/null 2>&1
{ while true ; do
      setxkbmap \
         -option \
         -option ctrl:nocaps \
         -option terminate:ctrl_alt_backspace \
         -option ctrl:menu_rctrl \
         -option keypad:pointerkeys

      xmodmap -e "keycode 135 = Super_L";
      xset r rate 350 50;
      xset s 3600
      sleep 10s;
done ; } &

numlockx

date
echo "New Session on $HOSTNAME" | figlet -w 1000

{ sleep 5s; xfsettingsd --no-daemon; } &
exec bash -c 'while true ; do awesome; sleep 1s; done;'
