#!/bin/zsh

cat ~/.xsession-errors > ~/.xsession-errors-1
echo > ~/.xsession-errors

unburden-home-dir

{ xfsettingsd --no-daemon; } &
{ sleep 6s; volti; } &
{ sleep 6s; cryptkeeper; } &

{ sleep 5s; awsetbg -l; } &

{ sleep 2s; conky ; }&

{ xbindkeys --nodaemon ; } &

date
echo "New Session on $HOSTNAME" | figlet -w 1000

#echo "Session: setting Xdefaults and Xmodmap"
#[ -e ~/.Xdefaults ] && xrdb -merge ~/.Xdefaults
#[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap > /dev/null 2>&1

xmodmap -e "keycode 135 = Super_L"

echo "Session: Setting Keyboard Repeat Rate 350ms delay 50hz repeat"
xset r rate 350 50

setxkbmap -option terminate:ctrl_alt_bksp
setxkbmap -option ctrl:nocaps
xset r rate 350 50

numlockx
{ sleep 3s; parcellite ; } &
{ sleep 3s; nm-applet ; } &

#synergys -d INFO -f &
#autocutsel -d -s PRIMARY &
#autocutsel -d -s CLIPBOARD &
#wicd-client &

#xscreensaver-command -exit > /dev/null || true
#xscreensaver -no-splash &

#{ while true; do
#    xmodmap -e 'remove Lock = Caps_Lock' >& /dev/null;
#    xmodmap -e 'keysym Caps_Lock = Control_L' >& /dev/null;
#    xmodmap -e 'add Control = Control_L' >& /dev/null;
#    xmodmap -e "keycode 135 = Super_L"
#    sleep 10s;
#done ; } &

#{ while true; do
#    nc v4address.com 23 | tail -n 1 | awk '{ print $5 }' > ~/.external_ip
#    tsocks nc v4address.com 23 | tail -n 1 | awk '{ print $5 }' > ~/.external_tor_ip
#    sleep 1m
#done ; } &

#gnome-power-manager &
#gnome-settings-daemon &
#update-notifier || true &
#
#uname -a
#
#{ sleep 5s; nitrogen --restore; } &
#{ sleep 9s; nitrogen --restore; } &
##{ sleep 30s; gnome-do; } &
#{ sleep 10s; pidgin; } &
{ sleep 1m; pidgin_fortune; } &
#{ sleep 1m; padevchooser; } &
#



#exec ssh-agent bash -c 'while true ; do awesome ; done;'
{ sleep 10s; awsetbg -l; } &
xrandr --output HDMI1 --primary
exec bash -c 'while true ; do awesome; sleep 1s; done;'

#exec ck-launch-session gnome-session
