#!/bin/zsh

start=$(date +%s.%N)

setopt allexport
nitrogen --restore &

{           xfsettingsd         --no-daemon                     ; } &
{ sleep 1s; xfce4-volumed                                       ; } &
{ sleep 1s; xfce4-power-manager --no-daemon                     ; } &

cat ~/.xsession-errors > ~/.xsession-errors-1
echo > ~/.xsession-errors
echo "New Session on $HOSTNAME" | figlet -w 1000

xrandr --output eDP1 --primary &
xgamma -gamma .8 &
{ compton -D 5 --config ~/.config/compton.conf                  ; } &
{ sleep 5s ; mpd; sleep 2s;  mpc pause                         ; } &
{ sleep 2m; ~/go/bin/mpdprxy --port 6600 \
      --hosts localhost:6601,localhost:6602 \
      --http 6610                                               ; } &
{ sleep 1m ; source ~/mopidy/bin/activate; mopidy               ; } &
{ sleep 5m  ; while true ; do mpdfavd        ; sleep 5s ; done  ; } &
{ sleep 5m  ; while true ; do mpdscribble --no-daemon ;
                                               sleep 5s ; done  ; } &
{ sleep 5m  ; while true ; do ~/bin/popup.py ; sleep 5s ; done  ; } &

{ conky                                                         ; } &
{ workrave                                                      ; } &

{ sleep 5s  ; nitrogen --restore                                ; } &

{ sleep 1s  ; clipit                                            ; } &
{ sleep 1s  ; solaar                                            ; } &
{ sleep 1s  ; xbacklight -set 80                                ; } &
{ sleep 1s  ; nm-applet                                         ; } &
{ sleep 1s  ; cryptkeeper                                       ; } &
{ sleep 1s  ; keynav                                            ; } &
{ sleep 1s  ; pasystray                                         ; } &
{ sleep 1s  ; fdpowermon                                        ; } &
{ sleep 1s  ; blueman-applet                                    ; } &
{ sleep 5s  ; xrandr --output DP1 --brightness .8               ; } &
{ sleep 5s  ; xrandr --output eDP1 --brightness .8              ; } &
{ sleep 5s  ; xrandr --output DP2-2 --brightness .8             ; } &
{ sleep 5s  ; xrandr --output DP2-3 --brightness .8             ; } &

{ sleep 90s  ; pidgin                                           ; } &
{ sleep 95s  ; ~/bin/pidgin_fortune                             ; } &
{ sleep 90s  ; claws-mail  2>&1 | fold -w 80 -s                 ; } &

{ sleep 1m  ;
      /opt/extras.ubuntu.com/calendar-indicator/bin/calendar-indicator 2>&1 \
            > /dev/null ; } &

echo "Session: setting Xdefaults and Xmodmap"
[ -e ~/.Xdefaults ] && xrdb -merge ~/.Xdefaults
[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap > /dev/null 2>&1
{ while true ; do
      setxkbmap \
         -option \
         -option ctrl:nocaps \
         -option terminate:ctrl_alt_bksp \
         -option ctrl:menu_rctrl \
         -option keypad:pointerkeys

      xmodmap -e "keycode 135 = Super_L";
      xset r rate 350 50;
      xset s 3600

      let GAP_Y=$(xrandr --current | grep primary | awk '{ print $4 }' | tr + ' ' | awk '{ print $3 }')+40
      sed "s/^gap_y.*/gap_y $GAP_Y/" < ~/Profile/conky-thinkpad1.conf > ~/tmp/conky-thinkpad1.conf

      if ! diff ~/Profile/conky-thinkpad1.conf ~/tmp/conky-thinkpad1.conf ; then
            mv -v ~/tmp/conky-thinkpad1.conf ~/Profile/conky-thinkpad1.conf
      fi

      local _PIDS=($(pgrep xfce4-volumed))
      if [[ "$_PIDS" ]]; then
            if (( "$(ps -o pmem h $_PIDS[1])" > 1 )); then
                  pkill $_PIDS;
                  { xfce4-volumed; } &
            fi
      fi

      sleep 10s;

done ; } &

numlockx

date
echo "New Session on $HOSTNAME" | figlet -w 1000

end=$(date +%s.%N)
let "duration = end - start"

sleep 1s

echo "###################################################"
echo "Session began in $duration seconds"
echo "###################################################"

exec bash -c 'while true ; do awesome; sleep 1s; done;'
