#!/bin/zsh
{  xfsettingsd --no-daemon; } &
cat ~/.xsession-errors > ~/.xsession-errors-1
echo > ~/.xsession-errors
echo "New Session on $HOSTNAME" | figlet -w 1000

unburden-home-dir
eval $(keychain --eval --nogui) 

xrandr --output VGA1 --primary
{ sleep 1s; xbindkeys --nodaemon ; } &

{ sleep 2s; awsetbg -l; sleep 1s; conky; } &

{ sleep 3s; parcellite ; } &
{ sleep 3s; nm-applet ; } &

{ sleep 5s; volti; } &
{ sleep 5s; pasystray; } &
{ sleep 6s; cryptkeeper; } &

echo "Session: setting Xdefaults and Xmodmap"
[ -e ~/.Xdefaults ] && xrdb -merge ~/.Xdefaults
[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap > /dev/null 2>&1
setxkbmap \
   -option\
   -option ctrl:nocaps\
   -option terminate:ctrl_alt_backspace\
   -option ctrl:menu_rctrl\
   -option keypad:pointerkeys

xmodmap -e "keycode 135 = Super_L"

echo "Session: Setting Keyboard Repeat Rate 350ms delay 50hz repeat"
xset r rate 350 50

numlockx &
feh --bg-scale Pictures/minimalwall-10-33-1-moleskine-minimal-wallpaper.png
date
echo "New Session on $HOSTNAME" | figlet -w 1000
exec bash -c 'while true ; do awesome; sleep 1s; done;'
