#!/usr/bin/perl 
#===============================================================================
#
#         FILE:  |FILENAME|
#
#        USAGE:  ./|FILENAME| 
#
#  DESCRIPTION:  |CURSOR|
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  |AUTHOR| (|AUTHORREF|), <|EMAIL|>
#      COMPANY:  |COMPANY|
#      VERSION:  1.0
#      CREATED:  |DATE|
#     REVISION:  $id$
#===============================================================================

use strict;
use warnings;



# vi: set ts=4 sw=4 et:
