-- automatically generated file. Do not edit (see /usr/share/doc/menu/html)

module("debian_menu")

debian_menu_Applications_Accessibility = {
	{"Xmag","xmag"},
}
debian_menu_Applications_Data_Management = {
	{"mytop", "x-terminal-emulator -e ".."/usr/bin/mytop"},
}
debian_menu_Applications_Editors = {
	{"Gedit","/usr/bin/gedit","/usr/share/pixmaps/gedit-icon.xpm"},
	{"GVIM","/usr/bin/vim.gnome -g -f","/usr/share/pixmaps/vim-32.xpm"},
	{"LeafPad","/usr/bin/leafpad","/usr/share/pixmaps/leafpad.xpm"},
	{"MousePad","/usr/bin/mousepad","/usr/share/pixmaps/mousepad.xpm"},
	{"Nano", "x-terminal-emulator -e ".."/bin/nano","/usr/share/nano/nano-menu.xpm"},
	{"Xedit","xedit"},
	{"Xfw File Writer","/usr/bin/xfilewriter","/usr/share/pixmaps/xfw.xpm"},
}
debian_menu_Applications_Education = {
	{"Arithmetic Quiz", "x-terminal-emulator -e ".."sh -c 'arithmetic;echo PRESS ENTER;read line'"},
}
debian_menu_Applications_File_Management = {
	{"Baobab","/usr/bin/baobab","/usr/share/pixmaps/baobab.xpm"},
	{"GNOME Search Tool","/usr/bin/gnome-search-tool","/usr/share/pixmaps/gsearchtool.xpm"},
	{"K3b","/usr/bin/k3b","/usr/share/pixmaps/k3b.xpm"},
	{"Nautilus","/usr/bin/nautilus","/usr/share/pixmaps/nautilus.xpm"},
	{"PCManFM","/usr/bin/pcmanfm"},
	{"Thunar","/usr/bin/thunar"},
	{"Time Traveling File Manager","/usr/bin/ttfm"},
	{"Xarchiver","/usr/bin/xarchiver","/usr/share/pixmaps/xarchiver.xpm"},
	{"Xfdesktop","xfdesktop"},
	{"Xfe File Manager","/usr/bin/xfe","/usr/share/pixmaps/xfe.xpm"},
	{"X file manager","/usr/bin/xfm","/usr/share/pixmaps/xfm_icon.xpm"},
}
debian_menu_Applications_Graphics = {
	{"dotty","/usr/bin/dotty"},
	{"FontForge","/usr/bin/fontforge","/usr/share/icons/ffanvil32.xpm"},
	{"gLabels","/usr/bin/glabels","/usr/share/pixmaps/glabels.xpm"},
	{"GNOME Screenshot Tool","/usr/bin/gnome-panel-screenshot"},
	{"gtkfontsel","gtkfontsel"},
	{"ImageMagick","/usr/bin/display logo:"},
	{"lefty","/usr/bin/lefty"},
	{"Mensis","/usr/bin/mensis"},
	{"OpenOffice.org Draw","/usr/bin/oodraw","/usr/share/icons/gnome/32x32/apps/openofficeorg24-draw.xpm"},
	{"The GIMP","/usr/bin/gimp","/usr/share/pixmaps/gimp.xpm"},
	{"XSane","/usr/bin/xsane","/usr/share/pixmaps/xsane.xpm"},
	{"X Window Snapshot","xwd | xwud"},
}
debian_menu_Applications_Mobile_Devices = {
	{"BitFling","/usr/bin/bitfling","/usr/share/pixmaps/bitfling.xpm"},
	{"BitPim","/usr/bin/bitpim","/usr/share/pixmaps/bitpim.xpm"},
}
debian_menu_Applications_Network_Communication = {
	{"Konversation IRC Client","/usr/bin/konversation","/usr/share/pixmaps/konversation32x32.xpm"},
	{"Mutt", "x-terminal-emulator -e ".."/usr/bin/mutt","/usr/share/pixmaps/mutt.xpm"},
	{"Pidgin","/usr/bin/pidgin","/usr/share/pixmaps/pidgin-menu.xpm"},
	{"Telnet-SSL", "x-terminal-emulator -e ".."/usr/bin/telnet-ssl"},
	{"Terminal Server Client","/usr/bin/tsclient -f","/usr/share/pixmaps/tsclient.xpm"},
	{"Thunderbird Mail","thunderbird","/usr/share/pixmaps/thunderbird.png"},
	{"Xbiff","xbiff"},
}
debian_menu_Applications_Network_File_Transfer = {
	{"cadaver", "x-terminal-emulator -e ".."/usr/bin/cadaver"},
	{"KTorrent","ktorrent","/usr/share/pixmaps/ktorrent.xpm"},
	{"Transmission BitTorrent Client","/usr/bin/transmission","/usr/share/pixmaps/transmission.xpm"},
}
debian_menu_Applications_Network_Monitoring = {
	{"jnettop", "x-terminal-emulator -e ".."/usr/bin/su-to-root -c /usr/sbin/jnettop"},
	{"KNetworkManager","/usr/bin/knetworkmanager"},
}
debian_menu_Applications_Network_Web_Browsing = {
	{"ELinks WWW browser", "x-terminal-emulator -e ".."/usr/bin/elinks"},
	{"Firefox 3 Browser","/usr/bin/firefox-3.0","/usr/share/pixmaps/firefox-3.0.png"},
	{"w3m", "x-terminal-emulator -e ".."/usr/bin/w3m /usr/share/doc/w3m/MANUAL.html"},
}
debian_menu_Applications_Network = {
	{"Communication",debian_menu_Applications_Network_Communication},
	{"File Transfer",debian_menu_Applications_Network_File_Transfer},
	{"Lynx", "x-terminal-emulator -e ".."/usr/bin/lynx"},
	{"Monitoring",debian_menu_Applications_Network_Monitoring},
	{"ncftp", "x-terminal-emulator -e ".."/usr/bin/ncftp3"},
	{"SAMBA for KDE","/usr/bin/smb4k"},
	{"Web Browsing",debian_menu_Applications_Network_Web_Browsing},
	{"xSMBrowser","/usr/bin/xsmbrowser","/usr/share/pixmaps/xsmbrowser-mini.xpm"},
	{"xtightvncviewer","/usr/bin/xtightvncviewer"},
}
debian_menu_Applications_Office = {
	{"HPLIP Fax address book","/usr/bin/hp-fab","/usr/share/pixmaps/HPmenu.xpm"},
	{"HPLIP Fax utility","/usr/bin/hp-sendfax","/usr/share/pixmaps/HPmenu.xpm"},
	{"OpenOffice.org Calc","/usr/bin/oocalc","/usr/share/icons/gnome/32x32/apps/openofficeorg24-calc.xpm"},
	{"OpenOffice.org Impress","/usr/bin/ooimpress","/usr/share/icons/gnome/32x32/apps/openofficeorg24-impress.xpm"},
	{"OpenOffice.org Writer","/usr/bin/oowriter","/usr/share/icons/gnome/32x32/apps/openofficeorg24-writer.xpm"},
}
debian_menu_Applications_Programming = {
	{"ccmake", "x-terminal-emulator -e ".."/usr/bin/ccmake","/usr/share/pixmaps/cmake.xpm"},
	{"GDB", "x-terminal-emulator -e ".."/usr/bin/gdb"},
	{"Monodoc","/usr/bin/monodoc","/usr/share/pixmaps/monodoc.png"},
	{"Ocaml", "x-terminal-emulator -e ".."/usr/bin/ocaml","/usr/share/pixmaps/ocaml.xpm"},
	{"Sun Java 6 Web Start","/usr/lib/jvm/java-6-sun-1.6.0.10/bin/javaws -viewer","/usr/share/pixmaps/sun-java6.xpm"},
	{"Tclsh8.4", "x-terminal-emulator -e ".."/usr/bin/tclsh8.4"},
	{"TkWish8.4","x-terminal-emulator -e /usr/bin/wish8.4"},
	{"xcolors","/usr/bin/xcolors"},
}
debian_menu_Applications_Science_Electronics = {
	{"gtkterm","/usr/bin/gtkterm"},
}
debian_menu_Applications_Science_Geoscience = {
	{"wmweather+","/usr/bin/wmweather+"},
}
debian_menu_Applications_Science_Mathematics = {
	{"Bc", "x-terminal-emulator -e ".."/usr/bin/bc"},
	{"Dc", "x-terminal-emulator -e ".."/usr/bin/dc"},
	{"GCalcTool","/usr/bin/gcalctool","/usr/share/pixmaps/gcalctool.xpm"},
	{"OpenOffice.org Math","/usr/bin/oomath","/usr/share/icons/gnome/32x32/apps/openofficeorg24-math.xpm"},
	{"SpeedCrunch","/usr/bin/speedcrunch","/usr/share/pixmaps/speedcrunch.xpm"},
	{"Xcalc","xcalc"},
}
debian_menu_Applications_Science = {
	{"Electronics",debian_menu_Applications_Science_Electronics},
	{"Geoscience",debian_menu_Applications_Science_Geoscience},
	{"Mathematics",debian_menu_Applications_Science_Mathematics},
}
debian_menu_Applications_Shells = {
	{"Bash", "x-terminal-emulator -e ".."/bin/bash --login"},
	{"Dash", "x-terminal-emulator -e ".."/bin/dash -i"},
	{"Python (v2.4)", "x-terminal-emulator -e ".."/usr/bin/python2.4","/usr/share/pixmaps/python2.4.xpm"},
	{"Python (v2.5)", "x-terminal-emulator -e ".."/usr/bin/python2.5","/usr/share/pixmaps/python2.5.xpm"},
	{"screenie", "x-terminal-emulator -e ".."/usr/bin/screenie"},
	{"Sh", "x-terminal-emulator -e ".."/bin/sh --login"},
	{"Zsh", "x-terminal-emulator -e ".."/bin/zsh4"},
	{"Zsh (snapshot)", "x-terminal-emulator -e ".."/bin/zsh-beta"},
}
debian_menu_Applications_Sound = {
	{"Amarok","/usr/bin/amarok"},
	{"Ario","/usr/bin/ario","/usr/share/pixmaps/ario.xpm"},
	{"Audacious","/usr/bin/audacious"},
	{"aumix", "x-terminal-emulator -e ".."/usr/bin/aumix","/usr/share/pixmaps/icon_aumix.xpm"},
	{"Exaile","/usr/bin/exaile","/usr/share/pixmaps/exaile.xpm"},
	{"gbemol","/usr/bin/gbemol"},
	{"glurp","/usr/bin/glurp"},
	{"gmix (Gnome 2.0 Mixer)","/usr/bin/gnome-volume-control","/usr/share/pixmaps/gnome-mixer.xpm"},
	{"gmpc","/usr/bin/gmpc","/usr/share/pixmaps/gmpc.xpm"},
	{"grecord (GNOME 2.0 Recorder)","/usr/bin/gnome-sound-recorder","/usr/share/pixmaps/gnome-grecord.xpm"},
	{"gtkpod","/usr/bin/gtkpod","/usr/share/pixmaps/gtkpod-icon-32x32.xpm"},
	{"JACK Control","/usr/bin/qjackctl","/usr/share/pixmaps/qjackctl.xpm"},
	{"padevchooser","/usr/bin/padevchooser"},
	{"paman","/usr/bin/paman"},
	{"paprefs","/usr/bin/paprefs"},
	{"pavucontrol","/usr/bin/pavucontrol"},
	{"pavumeter","/usr/bin/pavumeter"},
	{"Potamus","/usr/bin/potamus","/usr/share/pixmaps/potamus.xpm"},
	{"Pygmy","/usr/bin/pygmy"},
	{"pympd","/usr/bin/pympd"},
	{"Sonata","/usr/bin/sonata","/usr/share/pixmaps/sonata.xpm"},
	{"Sound Juicer","/usr/bin/sound-juicer","/usr/share/pixmaps/sound-juicer.xpm"},
	{"vumeter (Gnome 2.0 Volume Meter)","/usr/bin/vumeter","/usr/share/pixmaps/gnome-vumeter.xpm"},
	{"vux", "x-terminal-emulator -e ".."/usr/bin/vux"},
	{"WMMixer","/usr/bin/wmmixer"},
	{"WMMixer (Docked)","/usr/bin/wmmixer -w"},
	{"xfmedia","/usr/bin/xfmedia"},
}
debian_menu_Applications_System_Administration = {
	{"alsaconf", "x-terminal-emulator -e ".."su-to-root -p root -c /usr/sbin/alsaconf"},
	{"Aptitude", "x-terminal-emulator -e ".."/usr/bin/aptitude"},
	{"choose wm","/usr/bin/choosewm -c"},
	{"Debian Task selector", "x-terminal-emulator -e ".."su-to-root -c tasksel"},
	{"DSL/PPPoE configuration tool", "x-terminal-emulator -e ".."/usr/sbin/pppoeconf","/usr/share/pixmaps/pppoeconf.xpm"},
	{"Editres","editres"},
	{"fetchmailconf","/usr/bin/fetchmailconf","/usr/share/pixmaps/fetchmailconf.xpm"},
	{"fontmatrix","/usr/bin/fontmatrix"},
	{"Gnome Control Center","/usr/bin/gnome-control-center","/usr/share/pixmaps/control-center2.xpm"},
	{"GTK+ 2.0 theme manager","/usr/bin/gtk-chtheme","/usr/share/pixmaps/gtk-chtheme.xpm"},
	{"GTK+ 2.0 Theme Switch","/usr/bin/switch2"},
	{"HPLIP File printing","/usr/bin/hp-print","/usr/share/pixmaps/HPmenu.xpm"},
	{"Openbox Configuration Manager","/usr/bin/obconf","/usr/share/pixmaps/obconf.xpm"},
	{"pppconfig", "x-terminal-emulator -e ".."su-to-root -p root -c /usr/sbin/pppconfig"},
	{"QtConfig","/usr/bin/qtconfig-qt4"},
	{"reportbug", "x-terminal-emulator -e ".."/usr/bin/reportbug --exit-prompt"},
	{"Services Admin","/usr/bin/services-admin","/usr/share/gnome-system-tools/pixmaps/services.xpm"},
	{"Shares Admin","/usr/bin/shares-admin","/usr/share/gnome-system-tools/pixmaps/shares.xpm"},
	{"stalonetray","/usr/bin/stalonetray"},
	{"Sun Java 6 Plugin Control Panel","/usr/lib/jvm/java-6-sun-1.6.0.10/bin/ControlPanel","/usr/share/pixmaps/sun-java6.xpm"},
	{"sysvconfig", "x-terminal-emulator -e ".."/usr/bin/su-to-root -p root -c /usr/sbin/sysvconfig"},
	{"TeXconfig", "x-terminal-emulator -e ".."/usr/bin/texconfig"},
	{"Time Admin","/usr/bin/time-admin","/usr/share/gnome-system-tools/pixmaps/time.xpm"},
	{"User accounts Admin","/usr/bin/users-admin","/usr/share/gnome-system-tools/pixmaps/users.xpm"},
	{"Xclipboard","xclipboard"},
	{"Xfce-setting-show","xfce-setting-show","/usr/share/pixmaps/xfce4-mcs-manager.xpm"},
	{"Xfontsel","xfontsel"},
	{"xfprint4","xfprint4"},
	{"XFrun4","xfrun4"},
	{"Xkill","xkill"},
	{"Xrefresh","xrefresh"},
}
debian_menu_Applications_System_Hardware = {
	{"GNOME Floppy Formatter","/usr/bin/gfloppy","/usr/share/pixmaps/gfloppy.xpm"},
	{"HPLIP Toolbox","/usr/bin/hp-toolbox","/usr/share/pixmaps/HPmenu.xpm"},
	{"Xvidtune","xvidtune"},
}
debian_menu_Applications_System_Monitoring = {
	{"Conky", "x-terminal-emulator -e ".."/usr/bin/conky"},
	{"gdesklets","/usr/bin/gdesklets"},
	{"GKrellM","/usr/bin/gkrellm","/usr/share/pixmaps/gkrellm.xpm"},
	{"GNOME Log Viewer","/usr/bin/gnome-system-log","/usr/share/pixmaps/gnome-system-log.xpm"},
	{"KPowersave","/usr/bin/kpowersave","/usr/share/pixmaps/kpowersave.xpm"},
	{"Pstree", "x-terminal-emulator -e ".."/usr/bin/pstree.x11","/usr/share/pixmaps/pstree16.xpm"},
	{"Top", "x-terminal-emulator -e ".."/usr/bin/top"},
	{"wmsysmon","/usr/bin/wmsysmon"},
	{"wmtop","/usr/bin/wmtop"},
	{"Xconsole","xconsole -file /dev/xconsole"},
	{"Xev","x-terminal-emulator -e xev"},
	{"Xload","xload"},
}
debian_menu_Applications_System_Package_Management = {
	{"Synaptic Package Manager","/usr/bin/gksu /usr/sbin/synaptic","/usr/share/synaptic/pixmaps/synaptic_32x32.xpm"},
	{"Xfp Package Manager","/usr/bin/xfilepackage","/usr/share/pixmaps/xfp.xpm"},
}
debian_menu_Applications_System_Security = {
	{"Blueproximity","/usr/bin/blueproximity","/usr/share/pixmaps/blueproximity.xpm"},
	{"Sun Java 6 Policy Tool","/usr/lib/jvm/java-6-sun-1.6.0.10/bin/policytool","/usr/share/pixmaps/sun-java6.xpm"},
}
debian_menu_Applications_System = {
	{"Administration",debian_menu_Applications_System_Administration},
	{"fbpanel","/usr/bin/fbpanel"},
	{"GNOME system monitor","/usr/bin/gnome-system-monitor"},
	{"Hardware",debian_menu_Applications_System_Hardware},
	{"Monitoring",debian_menu_Applications_System_Monitoring},
	{"Openbox Menu Editor","/usr/bin/obmenu"},
	{"Package Management",debian_menu_Applications_System_Package_Management},
	{"PerlPanel","/usr/bin/perlpanel","/usr/share/pixmaps/perlpanel.xpm"},
	{"ROX Filer","/usr/bin/rox"},
	{"Security",debian_menu_Applications_System_Security},
	{"xbindkeys","/usr/bin/xbindkeys"},
}
debian_menu_Applications_Terminal_Emulators = {
	{"Aterm","/usr/bin/aterm"},
	{"Eterm","/usr/bin/Eterm"},
	{"evilvte","/usr/bin/evilvte","/usr/share/pixmaps/evilvte.xpm"},
	{"Gnome Terminal","/usr/bin/gnome-terminal","/usr/share/pixmaps/gnome-terminal.xpm"},
	{"mrxvt","/usr/bin/mrxvt-full"},
	{"mrxvt-cjk","/usr/bin/mrxvt-cjk"},
	{"mrxvt-mini","/usr/bin/mrxvt-mini"},
	{"ROXTerm","/usr/bin/roxterm","/usr/share/pixmaps/roxterm.xpm"},
	{"Rxvt","/usr/bin/rxvt-xterm"},
	{"Rxvt-Unicode","urxvt","/usr/share/pixmaps/urxvt.xpm"},
	{"Rxvt-Unicode (Black,Xft)","urxvt -fn \"xft:Courier New\" -rv","/usr/share/pixmaps/urxvt.xpm"},
	{"Terminal","/usr/bin/xfce4-terminal","/usr/share/pixmaps/terminal.xpm"},
	{"Tilda terminal","/usr/bin/tilda"},
	{"Wterm","/usr/bin/wterm"},
	{"Xfterm4", "x-terminal-emulator -e ".."xfterm4"},
	{"XTerm","xterm","/usr/share/pixmaps/xterm-color_32x32.xpm"},
	{"X-Terminal as root (GKsu)","/usr/bin/gksu -u root /usr/bin/x-terminal-emulator","/usr/share/pixmaps/gksu-debian.xpm"},
	{"XTerm (Unicode)","uxterm","/usr/share/pixmaps/xterm-color_32x32.xpm"},
	{"Xvt","/usr/bin/xvt -ls"},
	{"YaKuake","/usr/bin/yakuake"},
	{"yeahconsole","/usr/bin/yeahconsole"},
}
debian_menu_Applications_Text = {
	{"Character map","/usr/bin/gucharmap"},
	{"DAV Text Editor", "x-terminal-emulator -e ".."/usr/bin/dav"},
	{"dvtm", "x-terminal-emulator -e ".."/usr/bin/dvtm"},
	{"Fortune","sh -c 'while /usr/games/fortune | col -x | xmessage -center -buttons OK:1,Another:0 -default OK -file - ; do :; done'"},
	{"GNOME Dictionary","/usr/bin/gnome-dictionary","/usr/share/pixmaps/gdict.xpm"},
}
debian_menu_Applications_Tools = {
	{"adesklets","/usr/bin/adesklets"},
	{"docker","/usr/bin/docker"},
	{"fbpager","/usr/bin/fbpager"},
	{"fbxkb","/usr/bin/fbxkb"},
	{"fluxconf","/usr/bin/fluxconf"},
	{"fluxkeys","/usr/bin/fluxkeys"},
	{"fluxmenu","/usr/bin/fluxmenu"},
	{"KMobileTools","/usr/bin/kmobiletools"},
	{"Multisync","/usr/bin/multisync"},
	{"obextool","/usr/bin/obextool"},
	{"pypanel","/usr/bin/pypanel"},
	{"wininfo","/usr/bin/wininfo"},
	{"wmcliphist","/usr/bin/wmcliphist"},
	{"wmfire","/usr/bin/wmfire"},
	{"XBindKeys-config","/usr/bin/xbindkeys-config"},
	{"xcb","/usr/X11R6/bin/xcb"},
	{"Xcolorsel","/usr/bin/xcolorsel"},
	{"xvkbd","/usr/bin/xvkbd"},
}
debian_menu_Applications_Video = {
	{"totem (GStreamer)","/usr/bin/totem-gstreamer","/usr/share/pixmaps/totem.xpm"},
}
debian_menu_Applications_Viewers = {
	{"Tkfont","tkfont"},
	{"Xditview","xditview"},
	{"XDvi","/usr/bin/xdvi"},
	{"Xfi Image Viewer","/usr/bin/xfileimage","/usr/share/pixmaps/xfi.xpm"},
	{"Xfv File Viewer","/usr/bin/xfileview","/usr/share/pixmaps/xfv.xpm"},
	{"XLess","xless /usr/share/doc/xless/xless.help"},
	{"Xpdf","/usr/bin/xpdf","/usr/share/pixmaps/xpdf.xpm"},
}
debian_menu_Applications = {
	{"Accessibility",debian_menu_Applications_Accessibility},
	{"Data Management",debian_menu_Applications_Data_Management},
	{"Editors",debian_menu_Applications_Editors},
	{"Education",debian_menu_Applications_Education},
	{"File Management",debian_menu_Applications_File_Management},
	{"Graphics",debian_menu_Applications_Graphics},
	{"Mobile Devices",debian_menu_Applications_Mobile_Devices},
	{"Network",debian_menu_Applications_Network},
	{"Office",debian_menu_Applications_Office},
	{"Programming",debian_menu_Applications_Programming},
	{"Science",debian_menu_Applications_Science},
	{"Shells",debian_menu_Applications_Shells},
	{"Sound",debian_menu_Applications_Sound},
	{"System",debian_menu_Applications_System},
	{"Terminal Emulators",debian_menu_Applications_Terminal_Emulators},
	{"Text",debian_menu_Applications_Text},
	{"Tools",debian_menu_Applications_Tools},
	{"Video",debian_menu_Applications_Video},
	{"Viewers",debian_menu_Applications_Viewers},
}
debian_menu_Games_Action = {
	{"Robots", "x-terminal-emulator -e ".."robots"},
	{"Snake", "x-terminal-emulator -e ".."sh -c 'snake;echo PRESS ENTER;read line'"},
	{"Star Trek", "x-terminal-emulator -e ".."trek"},
	{"Worm", "x-terminal-emulator -e ".."sh -c 'worm;echo PRESS ENTER;read line'"},
}
debian_menu_Games_Adventure = {
	{"Adventure", "x-terminal-emulator -e ".."adventure"},
	{"Battlestar", "x-terminal-emulator -e ".."sh -c 'battlestar;echo PRESS ENTER;read line'"},
	{"Hack", "x-terminal-emulator -e ".."hack"},
	{"Hunt the Wumpus", "x-terminal-emulator -e ".."wump"},
	{"Phantasia", "x-terminal-emulator -e ".."phantasia"},
}
debian_menu_Games_Blocks = {
	{"Bsd Tetris", "x-terminal-emulator -e ".."sh -c 'tetris-bsd;echo;echo PRESS ENTER;read line'"},
}
debian_menu_Games_Board = {
	{"Backgammon", "x-terminal-emulator -e ".."backgammon -pb"},
	{"Gomoku", "x-terminal-emulator -e ".."gomoku"},
	{"Monopoly", "x-terminal-emulator -e ".."monop"},
}
debian_menu_Games_Card = {
	{"Canfield", "x-terminal-emulator -e ".."canfield"},
	{"Cribbage", "x-terminal-emulator -e ".."cribbage"},
	{"Go Fish", "x-terminal-emulator -e ".."sh -c 'go-fish;echo;echo PRESS ENTER;read line'"},
	{"Mille Bornes", "x-terminal-emulator -e ".."mille"},
}
debian_menu_Games_Puzzles = {
	{"Boggle", "x-terminal-emulator -e ".."boggle"},
	{"Hangman", "x-terminal-emulator -e ".."hangman"},
}
debian_menu_Games_Strategy = {
	{"Air Traffic Controller", "x-terminal-emulator -e ".."sh -c 'atc ; echo;echo PRESS ENTER;read line'"},
	{"Sail", "x-terminal-emulator -e ".."sail"},
}
debian_menu_Games_Tools = {
	{"Rclock","/usr/bin/rclock"},
}
debian_menu_Games_Toys = {
	{"Flip Screen","/usr/games/xflip"},
	{"idesk","/usr/bin/idesk"},
	{"Meltdown","/usr/games/meltdown"},
	{"Oclock","oclock"},
	{"Rain", "x-terminal-emulator -e ".."rain"},
	{"wmMatrix","/usr/bin/wmmatrix","/usr/share/icons/mini/wmMatrix.xpm"},
	{"Worms", "x-terminal-emulator -e ".."worms"},
	{"Xclock (analog)","xclock -analog"},
	{"Xclock (digital)","xclock -digital -update 1"},
	{"Xeyes","xeyes"},
	{"xfireworks","/usr/games/xfireworks"},
	{"Xlogo","xlogo"},
	{"Xpenguins - start","/usr/bin/xpenguins","/usr/share/pixmaps/xpenguins.xpm"},
	{"Xpenguins - stop","/usr/bin/xpenguins-stop","/usr/share/pixmaps/xpenguins.xpm"},
	{"Xsnow - Start","xsnow"},
	{"Xsnow - Stop","skill -c xsnow"},
}
debian_menu_Games = {
	{"Action",debian_menu_Games_Action},
	{"Adventure",debian_menu_Games_Adventure},
	{"Blocks",debian_menu_Games_Blocks},
	{"Board",debian_menu_Games_Board},
	{"Card",debian_menu_Games_Card},
	{"Puzzles",debian_menu_Games_Puzzles},
	{"Strategy",debian_menu_Games_Strategy},
	{"Tools",debian_menu_Games_Tools},
	{"Toys",debian_menu_Games_Toys},
}
debian_menu_Help = {
	{"Info", "x-terminal-emulator -e ".."info"},
	{"TeXdoctk","/usr/bin/texdoctk"},
	{"Xfce4-about","xfce4-about"},
	{"Xfhelp4","xfhelp4"},
	{"Xman","xman"},
	{"yelp","/usr/bin/yelp"},
}
debian_menu_Screen_Lock_Assorted = {
	{"Anemone","/usr/bin/xlock -remote -nice 19 -mode anemone"},
	{"Ball","/usr/bin/xlock -remote -nice 19 -mode ball"},
	{"Blot","/usr/bin/xlock -remote -nice 19 -mode blot"},
	{"Bounce","/usr/bin/xlock -remote -nice 19 -mode bounce"},
	{"Bubble","/usr/bin/xlock -remote -nice 19 -mode bubble"},
	{"Clock","/usr/bin/xlock -remote -nice 19 -mode clock"},
	{"Crystal","/usr/bin/xlock -remote -nice 19 -mode crystal"},
	{"Daisy","/usr/bin/xlock -remote -nice 19 -mode daisy"},
	{"Dclock","/usr/bin/xlock -remote -nice 19 -mode dclock"},
	{"Decay","/usr/bin/xlock -remote -nice 19 -mode decay"},
	{"Deco","/usr/bin/xlock -remote -nice 19 -mode deco"},
	{"Deluxe","/usr/bin/xlock -remote -nice 19 -mode deluxe"},
	{"Eyes","/usr/bin/xlock -remote -nice 19 -mode eyes +trackmouse"},
	{"Eyesptr","/usr/bin/xlock -remote -nice 19 -mode eyes -trackmouse"},
	{"Fiberlamp","/usr/bin/xlock -remote -nice 19 -mode fiberlamp"},
	{"Fzort","/usr/bin/xlock -remote -nice 19 -mode fzort"},
	{"Goop","/usr/bin/xlock -remote -nice 19 -mode goop"},
	{"Juggle","/usr/bin/xlock -remote -nice 19 -mode juggle"},
	{"Marquee","/usr/bin/xlock -remote -nice 19 -mode marquee"},
	{"Matrix","/usr/bin/xlock -remote -nice 19 -mode matrix"},
	{"Munch","/usr/bin/xlock -remote -nice 19 -mode munch"},
	{"Nose","/usr/bin/xlock -remote -nice 19 -mode nose"},
	{"Pacman","/usr/bin/xlock -remote -nice 19 -mode pacman"},
	{"Pyro","/usr/bin/xlock -remote -nice 19 -mode pyro +use3d"},
	{"Pyro3d","/usr/bin/xlock -remote -nice 19 -mode pyro -use3d"},
	{"Roll","/usr/bin/xlock -remote -nice 19 -mode roll"},
	{"Slip","/usr/bin/xlock -remote -nice 19 -mode slip"},
	{"Solitare","/usr/bin/xlock -remote -nice 19 -mode solitare +trackmouse"},
	{"Solitareptr","/usr/bin/xlock -remote -nice 19 -mode solitare -trackmouse"},
	{"Starfish","/usr/bin/xlock -remote -nice 19 -mode starfish -install"},
	{"Swarm","/usr/bin/xlock -remote -nice 19 -mode swarm +trackmouse"},
	{"Swarmptr","/usr/bin/xlock -remote -nice 19 -mode swarm -trackmouse"},
	{"Swirl","/usr/bin/xlock -remote -nice 19 -mode swirl -install"},
	{"T3d","/usr/bin/xlock -remote -nice 19 -mode t3d"},
	{"Tetris","/usr/bin/xlock -remote -nice 19 -mode tetris"},
	{"Tube","/usr/bin/xlock -remote -nice 19 -mode tube -install"},
	{"Worm","/usr/bin/xlock -remote -nice 19 -mode worm +use3d"},
	{"Worm3d","/usr/bin/xlock -remote -nice 19 -mode worm -use3d"},
	{"Xcl","/usr/bin/xlock -remote -nice 19 -mode xcl"},
	{"Xjack","/usr/bin/xlock -remote -nice 19 -mode xjack"},
}
debian_menu_Screen_Lock_Automata = {
	{"Ant","/usr/bin/xlock -remote -nice 19 -mode ant -neighbors 4 +truchet"},
	{"Ant3d","/usr/bin/xlock -remote -nice 19 -mode ant3d"},
	{"Ant Truchet","/usr/bin/xlock -remote -nice 19 -mode ant -neighbors 4 -truchet"},
	{"Bee","/usr/bin/xlock -remote -nice 19 -mode ant -neighbors 6 +truchet"},
	{"Bee Truchet","/usr/bin/xlock -remote -nice 19 -mode ant -neighbors 6 -truchet"},
	{"Bug","/usr/bin/xlock -remote -nice 19 -mode bug"},
	{"Demon","/usr/bin/xlock -remote -nice 19 -mode demon"},
	{"Dilemma","/usr/bin/xlock -remote -nice 19 -mode dilemma"},
	{"Life","/usr/bin/xlock -remote -nice 19 -mode life"},
	{"Life1d","/usr/bin/xlock -remote -nice 19 -mode life1d"},
	{"Life3d","/usr/bin/xlock -remote -nice 19 -mode life3d"},
	{"Life Callahan","/usr/bin/xlock -remote -nice 19 -mode life -callahan -size 7"},
	{"Loop","/usr/bin/xlock -remote -nice 19 -mode loop"},
	{"Petri","/usr/bin/xlock -remote -nice 19 -mode petri"},
	{"Random","/usr/bin/xlock -remote -nice 19 -mode random -modelist allautomata -fullrandom -neighbors 0"},
	{"Voters","/usr/bin/xlock -remote -nice 19 -mode voters"},
	{"Wator","/usr/bin/xlock -remote -nice 19 -mode wator"},
	{"Wire","/usr/bin/xlock -remote -nice 19 -mode wire"},
}
debian_menu_Screen_Lock_Fractal = {
	{"Coral","/usr/bin/xlock -remote -nice 19 -mode coral"},
	{"Discrete","/usr/bin/xlock -remote -nice 19 -mode discrete"},
	{"Dragon","/usr/bin/xlock -remote -nice 19 -mode dragon"},
	{"Drift","/usr/bin/xlock -remote -nice 19 -mode drift -fullrandom"},
	{"Euler2d","/usr/bin/xlock -remote -nice 19 -mode euler2d"},
	{"Flame","/usr/bin/xlock -remote -nice 19 -mode flame"},
	{"Flow","/usr/bin/xlock -remote -nice 19 -mode flow"},
	{"Forest","/usr/bin/xlock -remote -nice 19 -mode forest"},
	{"Hop","/usr/bin/xlock -remote -nice 19 -mode hop -fullrandom"},
	{"IFS","/usr/bin/xlock -remote -nice 19 -mode ifs"},
	{"Julia","/usr/bin/xlock -remote -nice 19 -mode julia +trackmouse"},
	{"Juliaptr","/usr/bin/xlock -remote -nice 19 -mode julia -trackmouse"},
	{"Kumppa","/usr/bin/xlock -remote -nice 19 -mode kumppa"},
	{"Lightning","/usr/bin/xlock -remote -nice 19 -mode lightning"},
	{"Lyapunov","/usr/bin/xlock -remote -nice 19 -mode lyapunov -install"},
	{"Mandelbrot","/usr/bin/xlock -remote -nice 19 -mode mandelbrot -install"},
	{"Mountain","/usr/bin/xlock -remote -nice 19 -mode mountain"},
	{"Random","/usr/bin/xlock -remote -nice 19 -mode random -modelist allfractal -fullrandom"},
	{"Sierpinski","/usr/bin/xlock -remote -nice 19 -mode sierpinski"},
	{"Strange","/usr/bin/xlock -remote -nice 19 -mode strange"},
	{"Thornbird","/usr/bin/xlock -remote -nice 19 -mode thornbird"},
	{"Triangle","/usr/bin/xlock -remote -nice 19 -mode triangle"},
	{"Turtle","/usr/bin/xlock -remote -nice 19 -mode turtle"},
	{"Vines","/usr/bin/xlock -remote -nice 19 -mode vines"},
}
debian_menu_Screen_Lock_Geometry = {
	{"Apollonian","/usr/bin/xlock -remote -nice 19 -mode apollonian"},
	{"Braid","/usr/bin/xlock -remote -nice 19 -mode braid"},
	{"Fadeplot","/usr/bin/xlock -remote -nice 19 -mode fadeplot"},
	{"Helix","/usr/bin/xlock -remote -nice 19 -mode helix -fullrandom"},
	{"Hyper","/usr/bin/xlock -remote -nice 19 -mode hyper"},
	{"Ico","/usr/bin/xlock -remote -nice 19 -mode ico"},
	{"Kaleid","/usr/bin/xlock -remote -nice 19 -mode kaleid"},
	{"Laser","/usr/bin/xlock -remote -nice 19 -mode laser"},
	{"Lisa","/usr/bin/xlock -remote -nice 19 -mode lisa"},
	{"Lissie","/usr/bin/xlock -remote -nice 19 -mode lissie"},
	{"Penrose","/usr/bin/xlock -remote -nice 19 -mode penrose +ammann"},
	{"Penrose Ammann","/usr/bin/xlock -remote -nice 19 -mode penrose -ammann"},
	{"Petal","/usr/bin/xlock -remote -nice 19 -mode petal"},
	{"Polyominoes","/usr/bin/xlock -remote -nice 19 -mode polyominoes"},
	{"Qix","/usr/bin/xlock -remote -nice 19 -mode qix +complete"},
	{"Qix complete","/usr/bin/xlock -remote -nice 19 -mode qix -complete"},
	{"Random","/usr/bin/xlock -remote -nice 19 -mode random -modelist allgeometry -fullrandom"},
	{"Rotor","/usr/bin/xlock -remote -nice 19 -mode rotor"},
	{"Shape","/usr/bin/xlock -remote -nice 19 -mode shape"},
	{"Sphere","/usr/bin/xlock -remote -nice 19 -mode sphere"},
	{"Spiral","/usr/bin/xlock -remote -nice 19 -mode spiral"},
	{"Spline","/usr/bin/xlock -remote -nice 19 -mode spline"},
	{"Tik_Tak","/usr/bin/xlock -remote -nice 19 -mode tik_tak"},
	{"Toneclock","/usr/bin/xlock -remote -nice 19 -mode toneclock"},
}
debian_menu_Screen_Lock_GLmodes = {
	{"Atlantis","/usr/bin/xlock -remote -nice 19 -mode atlantis"},
	{"Atunnels","/usr/bin/xlock -remote -nice 19 -mode atunnels"},
	{"Biof","/usr/bin/xlock -remote -nice 19 -mode biof"},
	{"Bubble3d","/usr/bin/xlock -remote -nice 19 -mode bubble3d"},
	{"Cage","/usr/bin/xlock -remote -nice 19 -mode cage"},
	{"Fire","/usr/bin/xlock -remote -nice 19 -mode fire"},
	{"Gears","/usr/bin/xlock -remote -nice 19 -mode gears"},
	{"GL-Planet","/usr/bin/xlock -remote -nice 19 -mode glplanet"},
	{"Invert","/usr/bin/xlock -remote -nice 19 -mode invert"},
	{"Lament","/usr/bin/xlock -remote -nice 19 -mode lament"},
	{"Moebius","/usr/bin/xlock -remote -nice 19 -mode moebius"},
	{"Molecule","/usr/bin/xlock -remote -nice 19 -mode molecule"},
	{"Morph3d","/usr/bin/xlock -remote -nice 19 -mode morph3d"},
	{"Noof","/usr/bin/xlock -remote -nice 19 -mode noof"},
	{"Pipes","/usr/bin/xlock -remote -nice 19 -mode pipes"},
	{"Random","/usr/bin/xlock -remote -nice 19 -mode random -modelist allgl -fullrandom"},
	{"Rubik","/usr/bin/xlock -remote -nice 19 -mode rubik"},
	{"Sballs","/usr/bin/xlock -remote -nice 19 -mode sballs"},
	{"Sierpinski3d","/usr/bin/xlock -remote -nice 19 -mode sierpinski3d"},
	{"Sproingies","/usr/bin/xlock -remote -nice 19 -mode sproingies"},
	{"Stairs","/usr/bin/xlock -remote -nice 19 -mode stairs"},
	{"Superquadrics","/usr/bin/xlock -remote -nice 19 -mode superquadrics"},
	{"Text3d","/usr/bin/xlock -remote -nice 19 -mode text3d -message \"$LOGNAME\""},
}
debian_menu_Screen_Lock_MarqueeMessage = {
	{"Back Soon","/usr/bin/xlock -remote -nice 19 -mode marquee -message \"$LOGNAME will be back soon.\""},
	{"Overnight","/usr/bin/xlock -remote -nice 19 -mode marquee -message \"$LOGNAME will be back in the morning.\""},
	{"Rude","/usr/bin/xlock -remote -nice 19 -mode marquee -message \"$LOGNAME not here, please go away!\""},
}
debian_menu_Screen_Lock_NoseMessage = {
	{"Back Soon","/usr/bin/xlock -remote -nice 19 -mode nose -message \"$LOGNAME will be back soon.\""},
	{"Overnight","/usr/bin/xlock -remote -nice 19 -mode nose -message \"$LOGNAME will be back in the morning.\""},
	{"Rude","/usr/bin/xlock -remote -nice 19 -mode nose -message \"$LOGNAME not here, please go away!\""},
}
debian_menu_Screen_Lock_Space = {
	{"Bouboule","/usr/bin/xlock -remote -nice 19 -mode bouboule +use3d"},
	{"Bouboule3d","/usr/bin/xlock -remote -nice 19 -mode bouboule -use3d"},
	{"Galaxy","/usr/bin/xlock -remote -nice 19 -mode galaxy"},
	{"Grav","/usr/bin/xlock -remote -nice 19 -mode grav +trail +decay"},
	{"Grav Decay","/usr/bin/xlock -remote -nice 19 -mode grav -decay"},
	{"Grav Trail","/usr/bin/xlock -remote -nice 19 -mode grav -trail"},
	{"Random Space","/usr/bin/xlock -remote -nice 19 -mode random -modelist allspace"},
	{"Rock","/usr/bin/xlock -remote -nice 19 -mode star -rock"},
	{"Space","/usr/bin/xlock -remote -nice 19 -mode space"},
	{"Star","/usr/bin/xlock -remote -nice 19 -mode star +rock +use3d +trek 0"},
	{"Star3d","/usr/bin/xlock -remote -nice 19 -mode star -use3d"},
	{"Star Trek","/usr/bin/xlock -remote -nice 19 -mode star -trek 100"},
	{"World","/usr/bin/xlock -remote -nice 19 -mode world"},
}
debian_menu_Screen_Lock_Special = {
	{"Blank","/usr/bin/xlock -remote -nice 19 -mode blank"},
	{"Bomb","/usr/bin/xlock -remote -nice 19 -mode bomb"},
	{"Random 3d","/usr/bin/xlock -remote -nice 19 -mode random -modelist all3d -use3d -fullrandom"},
	{"Random all","/usr/bin/xlock -remote -nice 19 -mode random -modelist all -fullrandom -neighbors 0"},
	{"Random nice","/usr/bin/xlock -remote -nice 19 -mode random -modelist allnice -fullrandom -neighbors 0"},
	{"Random ptr","/usr/bin/xlock -remote -nice 19 -mode random -modelist allmouse -trackmouse -fullrandom"},
	{"Random standard","/usr/bin/xlock -remote -nice 19 -mode random -modelist all-allgl -fullrandom -neighbors 0"},
	{"Random write","/usr/bin/xlock -remote -nice 19 -mode random -modelist allwrite -install -fullrandom"},
	{"Transparent","/usr/bin/xlock -remote -nice 19 -mode blank -geometry 1x1 -enablesaver"},
}
debian_menu_Screen_Lock_XjackMessage = {
	{"Crazy Boy","/usr/bin/xlock -remote -nice 19 -mode xjack -message \"All work and no play makes $LOGNAME a dull boy.\""},
	{"Crazy Girl","/usr/bin/xlock -remote -nice 19 -mode xjack -message \"All work and no play makes $LOGNAME a dull girl.\""},
}
debian_menu_Screen_Lock_XPM = {
	{"Bat","/usr/bin/xlock -remote -nice 19 -mode bat"},
	{"Flag","/usr/bin/xlock -remote -nice 19 -mode flag"},
	{"Image","/usr/bin/xlock -remote -nice 19 -mode image"},
	{"Life","/usr/bin/xlock -remote -nice 19 -mode life"},
	{"Life1d","/usr/bin/xlock -remote -nice 19 -mode life1d"},
	{"Maze","/usr/bin/xlock -remote -nice 19 -mode maze"},
	{"Puzzle","/usr/bin/xlock -remote -nice 19 -mode puzzle"},
	{"Random","/usr/bin/xlock -remote -nice 19 -mode random -modelist allxpm -fullrandom"},
}
debian_menu_Screen_Lock = {
	{"Assorted",debian_menu_Screen_Lock_Assorted},
	{"Automata",debian_menu_Screen_Lock_Automata},
	{"Fractal",debian_menu_Screen_Lock_Fractal},
	{"Geometry",debian_menu_Screen_Lock_Geometry},
	{"GLmodes",debian_menu_Screen_Lock_GLmodes},
	{"MarqueeMessage",debian_menu_Screen_Lock_MarqueeMessage},
	{"NoseMessage",debian_menu_Screen_Lock_NoseMessage},
	{"Space",debian_menu_Screen_Lock_Space},
	{"Special",debian_menu_Screen_Lock_Special},
	{"XjackMessage",debian_menu_Screen_Lock_XjackMessage},
	{"XPM",debian_menu_Screen_Lock_XPM},
}
debian_menu_Screen_Locking = {
	{"Lock Screen (XScreenSaver)","/usr/bin/xscreensaver-command -lock"},
	{"Xflock4", "x-terminal-emulator -e ".."xflock4"},
}
debian_menu_Screen_Save_Assorted = {
	{"Anemone","/usr/bin/xlock -remote -nice 19 -nolock -mode anemone"},
	{"Ball","/usr/bin/xlock -remote -nice 19 -nolock -mode ball"},
	{"Blot","/usr/bin/xlock -remote -nice 19 -nolock -mode blot"},
	{"Bounce","/usr/bin/xlock -remote -nice 19 -nolock -mode bounce"},
	{"Bubble","/usr/bin/xlock -remote -nice 19 -nolock -mode bubble"},
	{"Clock","/usr/bin/xlock -remote -nice 19 -nolock -mode clock"},
	{"Crystal","/usr/bin/xlock -remote -nice 19 -nolock -mode crystal"},
	{"Daisy","/usr/bin/xlock -remote -nice 19 -nolock -mode daisy"},
	{"Dclock","/usr/bin/xlock -remote -nice 19 -nolock -mode dclock"},
	{"Decay","/usr/bin/xlock -remote -nice 19 -nolock -mode decay"},
	{"Deco","/usr/bin/xlock -remote -nice 19 -nolock -mode deco"},
	{"Deluxe","/usr/bin/xlock -remote -nice 19 -nolock -mode deluxe"},
	{"Eyes","/usr/bin/xlock -remote -nice 19 -nolock -mode eyes +trackmouse"},
	{"Eyesptr","/usr/bin/xlock -remote -nice 19 -nolock -mode eyes -trackmouse"},
	{"Fiberlamp","/usr/bin/xlock -remote -nice 19 -nolock -mode fiberlamp"},
	{"Fzort","/usr/bin/xlock -remote -nice 19 -nolock -mode fzort"},
	{"Goop","/usr/bin/xlock -remote -nice 19 -nolock -mode goop"},
	{"Juggle","/usr/bin/xlock -remote -nice 19 -nolock -mode juggle"},
	{"Marquee","/usr/bin/xlock -remote -nice 19 -nolock -mode marquee"},
	{"Matrix","/usr/bin/xlock -remote -nice 19 -nolock -mode matrix"},
	{"Munch","/usr/bin/xlock -remote -nice 19 -nolock -mode munch"},
	{"Nose","/usr/bin/xlock -remote -nice 19 -nolock -mode nose"},
	{"Pacman","/usr/bin/xlock -remote -nice 19 -nolock -mode pacman"},
	{"Pyro","/usr/bin/xlock -remote -nice 19 -nolock -mode pyro +use3d"},
	{"Pyro3d","/usr/bin/xlock -remote -nice 19 -nolock -mode pyro -use3d"},
	{"Roll","/usr/bin/xlock -remote -nice 19 -nolock -mode roll"},
	{"Slip","/usr/bin/xlock -remote -nice 19 -nolock -mode slip"},
	{"Solitare","/usr/bin/xlock -remote -nice 19 -nolock -mode solitare +trackmouse"},
	{"Solitareptr","/usr/bin/xlock -remote -nice 19 -nolock -mode solitare -trackmouse"},
	{"Starfish","/usr/bin/xlock -remote -nice 19 -nolock -mode starfish -install"},
	{"Swarm","/usr/bin/xlock -remote -nice 19 -nolock -mode swarm +trackmouse"},
	{"Swarmptr","/usr/bin/xlock -remote -nice 19 -nolock -mode swarm -trackmouse"},
	{"Swirl","/usr/bin/xlock -remote -nice 19 -nolock -mode swirl -install"},
	{"T3d","/usr/bin/xlock -remote -nice 19 -nolock -mode t3d"},
	{"Tetris","/usr/bin/xlock -remote -nice 19 -nolock -mode tetris"},
	{"Tube","/usr/bin/xlock -remote -nice 19 -nolock -mode tube -install"},
	{"Worm","/usr/bin/xlock -remote -nice 19 -nolock -mode worm +use3d"},
	{"Worm3d","/usr/bin/xlock -remote -nice 19 -nolock -mode worm -use3d"},
	{"Xcl","/usr/bin/xlock -remote -nice 19 -nolock -mode xcl"},
	{"Xjack","/usr/bin/xlock -remote -nice 19 -nolock -mode xjack"},
}
debian_menu_Screen_Save_Automata = {
	{"Ant","/usr/bin/xlock -remote -nice 19 -nolock -mode ant -neighbors 4 +truchet"},
	{"Ant3d","/usr/bin/xlock -remote -nice 19 -nolock -mode ant3d"},
	{"Ant Truchet","/usr/bin/xlock -remote -nice 19 -nolock -mode ant -neighbors 4 -truchet"},
	{"Bee","/usr/bin/xlock -remote -nice 19 -nolock -mode ant -neighbors 6 +truchet"},
	{"Bee Truchet","/usr/bin/xlock -remote -nice 19 -nolock -mode ant -neighbors 6 -truchet"},
	{"Bug","/usr/bin/xlock -remote -nice 19 -nolock -mode bug"},
	{"Demon","/usr/bin/xlock -remote -nice 19 -nolock -mode demon"},
	{"Dilemma","/usr/bin/xlock -remote -nice 19 -nolock -mode dilemma"},
	{"Life","/usr/bin/xlock -remote -nice 19 -nolock -mode life"},
	{"Life1d","/usr/bin/xlock -remote -nice 19 -nolock -mode life1d"},
	{"Life3d","/usr/bin/xlock -remote -nice 19 -nolock -mode life3d"},
	{"Life Callahan","/usr/bin/xlock -remote -nice 19 -nolock -mode life -callahan -size 7"},
	{"Loop","/usr/bin/xlock -remote -nice 19 -nolock -mode loop"},
	{"Petri","/usr/bin/xlock -remote -nice 19 -nolock -mode petri"},
	{"Random","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allautomata -fullrandom -neighbors 0"},
	{"Voters","/usr/bin/xlock -remote -nice 19 -nolock -mode voters"},
	{"Wator","/usr/bin/xlock -remote -nice 19 -nolock -mode wator"},
	{"Wire","/usr/bin/xlock -remote -nice 19 -nolock -mode wire"},
}
debian_menu_Screen_Save_Fractal = {
	{"Coral","/usr/bin/xlock -remote -nice 19 -nolock -mode coral"},
	{"Discrete","/usr/bin/xlock -remote -nice 19 -nolock -mode discrete"},
	{"Dragon","/usr/bin/xlock -remote -nice 19 -nolock -mode dragon"},
	{"Drift","/usr/bin/xlock -remote -nice 19 -nolock -mode drift -fullrandom"},
	{"Euler2d","/usr/bin/xlock -remote -nice 19 -nolock -mode euler2d"},
	{"Flame","/usr/bin/xlock -remote -nice 19 -nolock -mode flame"},
	{"Flow","/usr/bin/xlock -remote -nice 19 -nolock -mode flow"},
	{"Forest","/usr/bin/xlock -remote -nice 19 -nolock -mode forest"},
	{"Hop","/usr/bin/xlock -remote -nice 19 -nolock -mode hop -fullrandom"},
	{"IFS","/usr/bin/xlock -remote -nice 19 -nolock -mode ifs"},
	{"Julia","/usr/bin/xlock -remote -nice 19 -nolock -mode julia +trackmouse"},
	{"Juliaptr","/usr/bin/xlock -remote -nice 19 -nolock -mode julia -trackmouse"},
	{"Kumppa","/usr/bin/xlock -remote -nice 19 -nolock -mode kumppa"},
	{"Lightning","/usr/bin/xlock -remote -nice 19 -nolock -mode lightning"},
	{"Lyapunov","/usr/bin/xlock -remote -nice 19 -nolock -mode lyapunov -install"},
	{"Mandelbrot","/usr/bin/xlock -remote -nice 19 -nolock -mode mandelbrot -install"},
	{"Mountain","/usr/bin/xlock -remote -nice 19 -nolock -mode mountain"},
	{"Random","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allfractal -fullrandom"},
	{"Sierpinski","/usr/bin/xlock -remote -nice 19 -nolock -mode sierpinski"},
	{"Strange","/usr/bin/xlock -remote -nice 19 -nolock -mode strange"},
	{"Thornbird","/usr/bin/xlock -remote -nice 19 -nolock -mode thornbird"},
	{"Triangle","/usr/bin/xlock -remote -nice 19 -nolock -mode triangle"},
	{"Turtle","/usr/bin/xlock -remote -nice 19 -nolock -mode turtle"},
	{"Vines","/usr/bin/xlock -remote -nice 19 -nolock -mode vines"},
}
debian_menu_Screen_Save_Geometry = {
	{"Apollonian","/usr/bin/xlock -remote -nice 19 -nolock -mode apollonian"},
	{"Braid","/usr/bin/xlock -remote -nice 19 -nolock -mode braid"},
	{"Fadeplot","/usr/bin/xlock -remote -nice 19 -nolock -mode fadeplot"},
	{"Helix","/usr/bin/xlock -remote -nice 19 -nolock -mode helix -fullrandom"},
	{"Hyper","/usr/bin/xlock -remote -nice 19 -nolock -mode hyper"},
	{"Ico","/usr/bin/xlock -remote -nice 19 -nolock -mode ico"},
	{"Kaleid","/usr/bin/xlock -remote -nice 19 -nolock -mode kaleid"},
	{"Laser","/usr/bin/xlock -remote -nice 19 -nolock -mode laser"},
	{"Lisa","/usr/bin/xlock -remote -nice 19 -nolock -mode lisa"},
	{"Lissie","/usr/bin/xlock -remote -nice 19 -nolock -mode lissie"},
	{"Penrose","/usr/bin/xlock -remote -nice 19 -nolock -mode penrose +ammann"},
	{"Penrose Ammann","/usr/bin/xlock -remote -nice 19 -nolock -mode penrose -ammann"},
	{"Petal","/usr/bin/xlock -remote -nice 19 -nolock -mode petal"},
	{"Polyominoes","/usr/bin/xlock -remote -nice 19 -nolock -mode polyominoes"},
	{"Qix","/usr/bin/xlock -remote -nice 19 -nolock -mode qix +complete"},
	{"Qix complete","/usr/bin/xlock -remote -nice 19 -nolock -mode qix -complete"},
	{"Random","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allgeometry"},
	{"Rotor","/usr/bin/xlock -remote -nice 19 -nolock -mode rotor"},
	{"Shape","/usr/bin/xlock -remote -nice 19 -nolock -mode shape"},
	{"Sphere","/usr/bin/xlock -remote -nice 19 -nolock -mode sphere"},
	{"Spiral","/usr/bin/xlock -remote -nice 19 -nolock -mode spiral"},
	{"Spline","/usr/bin/xlock -remote -nice 19 -nolock -mode spline"},
	{"Tik_Tak","/usr/bin/xlock -remote -nice 19 -nolock -mode tik_tak"},
	{"Toneclock","/usr/bin/xlock -remote -nice 19 -nolock -mode toneclock"},
}
debian_menu_Screen_Save_GLmodes = {
	{"Atlantis","/usr/bin/xlock -remote -nice 19 -nolock -mode atlantis"},
	{"Atunnels","/usr/bin/xlock -remote -nice 19 -nolock -mode atunnels"},
	{"Biof","/usr/bin/xlock -remote -nice 19 -nolock -mode biof"},
	{"Bubble3d","/usr/bin/xlock -remote -nice 19 -nolock -mode bubble3d"},
	{"Cage","/usr/bin/xlock -remote -nice 19 -nolock -mode cage"},
	{"Fire","/usr/bin/xlock -remote -nice 19 -nolock -mode fire"},
	{"Gears","/usr/bin/xlock -remote -nice 19 -nolock -mode gears"},
	{"GL-Planet","/usr/bin/xlock -remote -nice 19 -nolock -mode glplanet"},
	{"Lament","/usr/bin/xlock -remote -nice 19 -nolock -mode lament"},
	{"Moebius","/usr/bin/xlock -remote -nice 19 -nolock -mode moebius"},
	{"Molecule","/usr/bin/xlock -remote -nice 19 -nolock -mode molecule"},
	{"Morph3d","/usr/bin/xlock -remote -nice 19 -nolock -mode morph3d"},
	{"Noof","/usr/bin/xlock -remote -nice 19 -nolock -mode noof"},
	{"Pipes","/usr/bin/xlock -remote -nice 19 -nolock -mode pipes"},
	{"Random","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allgl -fullrandom"},
	{"Rubik","/usr/bin/xlock -remote -nice 19 -nolock -mode rubik"},
	{"Sballs","/usr/bin/xlock -remote -nice 19 -nolock -mode sballs"},
	{"Sierpinski3d","/usr/bin/xlock -remote -nice 19 -nolock -mode sierpinski3d"},
	{"Sproingies","/usr/bin/xlock -remote -nice 19 -nolock -mode sproingies"},
	{"Stairs","/usr/bin/xlock -remote -nice 19 -nolock -mode stairs"},
	{"Superquadrics","/usr/bin/xlock -remote -nice 19 -nolock -mode superquadrics"},
	{"Text3d","/usr/bin/xlock -remote -nice 19 -nolock -mode text3d -message \"$LOGNAME\""},
}
debian_menu_Screen_Save_MarqueeMessage = {
	{"Available","/usr/bin/xlock -remote -nice 19 -nolock -mode marquee -message \"Hey, I'm available now!\""},
	{"Brilliant!","/usr/bin/xlock -remote -nice 19 -nolock -mode marquee -message \"WOW! $LOGNAME, You're Brilliant!\""},
	{"Love You","/usr/bin/xlock -remote -nice 19 -nolock -mode marquee -message \"You know, I Love You $LOGNAME.\""},
}
debian_menu_Screen_Save_NoseMessage = {
	{"Available","/usr/bin/xlock -remote -nice 19 -nolock -mode nose -message \"Hey, I'm available now!\""},
	{"Brilliant!","/usr/bin/xlock -remote -nice 19 -nolock -mode nose -message \"WOW! $LOGNAME, You're Brilliant!\""},
	{"Love You","/usr/bin/xlock -remote -nice 19 -nolock -mode nose -message \"You know, I Love You $LOGNAME.\""},
}
debian_menu_Screen_Save_Space = {
	{"Bouboule","/usr/bin/xlock -remote -nice 19 -nolock -mode bouboule +use3d"},
	{"Bouboule3d","/usr/bin/xlock -remote -nice 19 -nolock -mode bouboule -use3d"},
	{"Galaxy","/usr/bin/xlock -remote -nice 19 -nolock -mode galaxy"},
	{"Grav","/usr/bin/xlock -remote -nice 19 -nolock -mode grav +trail +decay"},
	{"Grav Decay","/usr/bin/xlock -remote -nice 19 -nolock -mode grav -decay"},
	{"Grav Trail","/usr/bin/xlock -remote -nice 19 -nolock -mode grav -trail"},
	{"Random Space","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allspace"},
	{"Rock","/usr/bin/xlock -remote -nice 19 -nolock -mode star -rock"},
	{"Scooter","/usr/bin/xlock -remote -nice 19 -nolock -mode scooter"},
	{"Space","/usr/bin/xlock -remote -nice 19 -nolock -mode space"},
	{"Star","/usr/bin/xlock -remote -nice 19 -nolock -mode star +rock +use3d +trek 0"},
	{"Star3d","/usr/bin/xlock -remote -nice 19 -nolock -mode star -use3d"},
	{"Star Trek","/usr/bin/xlock -remote -nice 19 -nolock -mode star -trek 100"},
	{"World","/usr/bin/xlock -remote -nice 19 -nolock -mode world"},
}
debian_menu_Screen_Save_Special = {
	{"Blank","/usr/bin/xlock -remote -nice 19 -nolock -mode blank"},
	{"Bomb","/usr/bin/xlock -remote -nice 19 -nolock -mode bomb"},
	{"Random 3d","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist all3d -use3d -fullrandom"},
	{"Random all","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist all -fullrandom -neighbors 0"},
	{"Random nice","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allnice -fullrandom -neighbors 0"},
	{"Random ptr","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allmouse -trackmouse -fullrandom"},
	{"Random standard","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist all-allgl -fullrandom -neighbors 0"},
	{"Random write","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allwrite -fullrandom"},
}
debian_menu_Screen_Save_XPM = {
	{"Bat","/usr/bin/xlock -remote -nice 19 -nolock -mode bat"},
	{"Flag","/usr/bin/xlock -remote -nice 19 -nolock -mode flag"},
	{"Image","/usr/bin/xlock -remote -nice 19 -nolock -mode image"},
	{"Life","/usr/bin/xlock -remote -nice 19 -nolock -mode life"},
	{"Life1d","/usr/bin/xlock -remote -nice 19 -nolock -mode life1d"},
	{"Maze","/usr/bin/xlock -remote -nice 19 -nolock -mode maze"},
	{"Puzzle","/usr/bin/xlock -remote -nice 19 -nolock -mode puzzle"},
	{"Random","/usr/bin/xlock -remote -nice 19 -nolock -mode random -modelist allxpm -fullrandom"},
}
debian_menu_Screen_Save = {
	{"Assorted",debian_menu_Screen_Save_Assorted},
	{"Automata",debian_menu_Screen_Save_Automata},
	{"Fractal",debian_menu_Screen_Save_Fractal},
	{"Geometry",debian_menu_Screen_Save_Geometry},
	{"GLmodes",debian_menu_Screen_Save_GLmodes},
	{"MarqueeMessage",debian_menu_Screen_Save_MarqueeMessage},
	{"NoseMessage",debian_menu_Screen_Save_NoseMessage},
	{"Space",debian_menu_Screen_Save_Space},
	{"Special",debian_menu_Screen_Save_Special},
	{"XPM",debian_menu_Screen_Save_XPM},
}
debian_menu_Screen_Saving = {
	{"Activate ScreenSaver (Next)","/usr/bin/xscreensaver-command -next"},
	{"Activate ScreenSaver (Previous)","/usr/bin/xscreensaver-command -prev"},
	{"Activate ScreenSaver (Random)","/usr/bin/xscreensaver-command -activate"},
	{"Console Matrix (Text)", "x-terminal-emulator -e ".."/usr/bin/cmatrix"},
	{"Console Matrix (Virtual Console)", "x-terminal-emulator -e ".."/usr/bin/cmatrix -l"},
	{"Console Matrix (X11)","/usr/bin/cmatrix -x"},
	{"Demo Screen Hacks","/usr/bin/xscreensaver-command -demo"},
	{"Disable XScreenSaver","/usr/bin/xscreensaver-command -exit"},
	{"Enable XScreenSaver","/usr/bin/xscreensaver"},
	{"Reinitialize XScreenSaver","/usr/bin/xscreensaver-command -restart"},
	{"ScreenSaver Preferences","/usr/bin/xscreensaver-command -prefs"},
}
debian_menu_Screen = {
	{"Lock",debian_menu_Screen_Lock},
	{"Locking",debian_menu_Screen_Locking},
	{"Save",debian_menu_Screen_Save},
	{"Saving",debian_menu_Screen_Saving},
}
debian_menu_System_Administration = {
	{"Xfce Application Finder","xfce4-appfinder","/usr/share/pixmaps/xfce4-appfinder.xpm"},
}
debian_menu_System = {
	{"Administration",debian_menu_System_Administration},
}
debian_menu = {
	{"Applications",debian_menu_Applications},
	{"Games",debian_menu_Games},
	{"Help",debian_menu_Help},
	{"Screen",debian_menu_Screen},
	{"System",debian_menu_System},
}
